<?php

namespace App\Http\Controllers\Articles;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function getCategoryNews()
    {
        echo "getCategoryNews";
//        return parent::getCategory(); // TODO: Change the autogenerated stub
    }
}
